### ISSUE TITLE
Github Actions - Ruby 3.0.1

### ISSUE THREAD

**Issue by tiagocasanovapt** [miyataka/fcmpush#24]
Ruby 3.0.1 was released today - https://www.ruby-lang.org/en/news/2021/04/05/ruby-3-0-1-released/

And It started to present this message on github actions:

`_fcmpush-1.3.1 requires ruby version <= 3.0, >= 2.4, which is incompatible with the current version, ruby 3.0.1p64_`

The gemspec needs to be updated - https://github.com/miyataka/fcmpush/blob/main/fcmpush.gemspec

**Comment by miyataka** [comment]
@tiagocasanovapt 
Thanks for issue.
I'll do it.

**Comment by miyataka** [comment]
fixed. 
https://github.com/miyataka/fcmpush/commit/61e510b3c8eb82450c0e2ed232e1effbe73e3cb9

Thanks @tiagocasanovapt !!
