### ISSUE TITLE
Sender id mismatch 

### ISSUE THREAD

**Issue by petervandeput** [miyataka/fcmpush#30]
Always getting this error 
Please make clear overview which steps to take with fcm 
I think but don’t understand why the android app is using something different as the fcm credentials

**Comment by miyataka** [comment]
@petervandeput 
Thank you your issue report.

> I think but don’t understand why the android app is using something different as the fcm credentials

This article may help you.
https://firebase.google.com/docs/cloud-messaging/fcm-architecture

![image](https://user-images.githubusercontent.com/15692588/161575006-0605b6cb-4d32-4663-abf3-389524a81365.png)

This library, fcmpush cover here
![image](https://user-images.githubusercontent.com/15692588/161575294-ebb29e9b-9baf-4dcf-a5ab-69fc5db71072.png)

https://firebase.google.com/docs/cloud-messaging/fcm-architecture#lifecycle_flow
> Register devices to receive messages from FCM. An instance of a client app registers to receive messages, obtaining a registration token that uniquely identifies the app instance.

For this reason, Android(and other platform; iOS, Webpush), need firebase credentials for register devises.

Fcmpush require **Admin SDK** credentials for FCM backend(a.k.a. google) recognize us as a **Trusted Environment**.

I hope this helps.

**Comment by miyataka** [comment]
close this issue.
Please reopen if you need.
