### ISSUE TITLE
Configure multiple fcm account

### ISSUE THREAD

**Issue by dheenaINDIAN** [miyataka/fcmpush#33]
How can i configure multiple json_key_io and send notification to multiple firebase users

**Comment by miyataka** [comment]
@dheenaINDIAN 

[question]
- Do you want to configure fcmpush for multiple firebase project?
	- do you mentioned known bug? about [this](https://github.com/miyataka/fcmpush/issues/18)
- Or do you just want to send push-notification to multiple users in batch? 
	- use batch > https://github.com/miyataka/fcmpush#push-messages-in-batch
