### ISSUE TITLE
Server Key Deprecation

### ISSUE THREAD

**Issue by lackneets** [miyataka/fcmpush#40]
I recently received a notice from FCM indicating that the Server Key feature will be deprecated on June 20, 2024.

![CleanShot 2023-12-25 at 09 21 13](https://github.com/miyataka/fcmpush/assets/3694058/9dd68e39-8dc9-47f9-8a13-0c820b99e2a3)

However, I'm not sure if he meant the auth method that would affect subscribe/unsubscribe or if the entire API would be affected. [Google developer documentation](https://firebase.google.com/docs/cloud-messaging/auth-server#provide-credentials-manually) is so hard to read.

![CleanShot 2023-12-25 at 09 24 08](https://github.com/miyataka/fcmpush/assets/3694058/1ee7a401-b347-4cde-8a8d-f01992fc7c4d)

**Comment by ryy** [comment]
I have faced this problem [before](https://github.com/miyataka/fcmpush/pull/36#issuecomment-1614105403).
I tried to use `access_token` instead of `server_key` but it didn't work.

https://github.com/miyataka/fcmpush/blob/872a52830ddd3d228cc59fd6e773ed3ccce59a2e/lib/fcmpush/client.rb#L136-L141
```diff
def legacy_authorized_header(headers)
  headers.merge('Content-Type' => 'application/json',
                'Accept' => 'application/json',
-                'Authorization' => "Bearer #{server_key}"
+                'Authorization' => "Bearer #{access_token}")
end
```

```ruby
Fcmpush::Unauthorized: Received an error response 401 Unauthorized: <HTML>
<HEAD>
<TITLE>Unauthorized</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Unauthorized</H1>
<H2>Error 401</H2>
</BODY>
</HTML>
```

However, I found a way to make `subscribe` and `unsubscribe` work with `access_token`.

Could you please assign this issue to me?

**Comment by ryy** [comment]
Sorry, I'm not sure how to do this. I did not describe the solution.

Add the following to the header

`access_token_auth: true`.

ref: https://takanamito.hateblo.jp/entry/2020/07/04/175045


It works.

```ruby
# config/initializers/monkey_patches.rb

Dir[Rails.root.join('lib', 'monkey_patches', '**', '*.rb')].each do |file|
    require file
end
```

```ruby
# lib/monkey_patches/fcmpush/client.rb

module FcmPushMonkeyPatch
    module Client
      private
  
      def legacy_authorized_header(headers)
        headers.merge('Content-Type' => 'application/json',
                      'Accept' => 'application/json',
                      'Authorization' => "Bearer #{access_token}", # <- Change from server_key to access_token
                      'access_token_auth' => 'true') # <- add new header key value
      end
    end
end
  
Fcmpush::Client.prepend(FcmPushMonkeyPatch::Client)

```

**Comment by miyataka** [comment]
NOW, server_key is deprecated on v1.4.3!!

Thank you all!!
@lackneets @ryy
