### ISSUE TITLE
Batch send API was deprecated

### ISSUE THREAD

**Issue by vanso-hubsi** [miyataka/fcmpush#45]
Hi!

I just wanted to use the batch sending feature when I discovered that it was deprecated by Google June 20, 2023 and will be shut down June 21, 2024.
See here for details: https://firebase.google.com/support/faq/#fcm-depr-features

I suggest to add a warning to the feature and/or disable it.
And possible migrate to HTTP/2 as suggested.

**Comment by renanmedina** [comment]
I created a PR (https://github.com/miyataka/fcmpush/pull/47) to warn and raise an custom exception, but maybe the method can be removed completely since is already shutdown? 🤔 

👍🏻

**Comment by miyataka** [comment]
r
